### ISSUE TITLE
Refactor GameActivityCheckerJob

### ISSUE THREAD

**Issue by yaporyvaev** [yaporyvaev/Oracles-Lens#1]
Необходимо отрефакторить и переделать способ пуллинга в GameActivityCheckerJob

**TODO:**
- [x] GameParticipantsHelper не должен ходить в БД, передавать список игроков в конструкторе\аргументе статического метода
- [x] Вынести логику из джобы в доменный слой
- [x] Создать константы для QueueType

**Comment by yaporyvaev** [comment]
Done
